#!/usr/bin/env python3
"""Self-host the web fonts (no third-party requests at runtime).

Fetches the same Google Fonts CSS the app used, downloads the woff2 files
for the latin + latin-ext subsets (drops vietnamese), and writes:
  ../fonts/*.woff2   the font files
  ../fonts.css       @font-face rules pointing at the local files

Fonts: Fraunces, Spline Sans, Spline Sans Mono — all SIL Open Font License,
so self-hosting is permitted. Re-run to refresh.
"""
import os, re, urllib.request

HERE = os.path.dirname(__file__)
FONTS_DIR = os.path.join(HERE, "..", "fonts")
CSS_OUT = os.path.join(HERE, "..", "fonts.css")

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0 Safari/537.36")
SRC_CSS = ("https://fonts.googleapis.com/css2?"
           "family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600;9..144,700"
           "&family=Spline+Sans:wght@400;500;600"
           "&family=Spline+Sans+Mono:wght@400;500&display=swap")
KEEP_SUBSETS = {"latin", "latin-ext"}


def fetch(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req) as r:
        return r.read() if binary else r.read().decode("utf-8")


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def main():
    os.makedirs(FONTS_DIR, exist_ok=True)
    css = fetch(SRC_CSS)
    # Each block is preceded by a "/* subset */" comment then an @font-face {...}
    blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)
    out, saved = [], 0
    for subset, block in blocks:
        if subset not in KEEP_SUBSETS:
            continue
        fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
        style = re.search(r"font-style:\s*(\w+)", block).group(1)
        urange = re.search(r"unicode-range:\s*([^;]+);", block).group(1).strip()
        src_url = re.search(r"src:\s*url\(([^)]+)\)", block).group(1)

        name = f"{slug(fam)}-{weight}-{style}-{subset}.woff2"
        with open(os.path.join(FONTS_DIR, name), "wb") as f:
            f.write(fetch(src_url, binary=True))
        saved += 1

        out.append(
            "@font-face{\n"
            f"  font-family:'{fam}';\n"
            f"  font-style:{style};\n"
            f"  font-weight:{weight};\n"
            "  font-display:swap;\n"
            f"  src:url(fonts/{name}) format('woff2');\n"
            f"  unicode-range:{urange};\n"
            "}"
        )

    header = ("/* Self-hosted web fonts — generated by tools/fetch_fonts.py.\n"
              "   Fraunces, Spline Sans, Spline Sans Mono (SIL OFL).\n"
              "   No third-party requests at runtime. */\n")
    with open(CSS_OUT, "w") as f:
        f.write(header + "\n".join(out) + "\n")
    print(f"saved {saved} woff2 files -> {os.path.normpath(FONTS_DIR)}")
    print(f"wrote {os.path.normpath(CSS_OUT)}")


if __name__ == "__main__":
    main()
